### ISSUE TITLE
Error running rsim.run

### ISSUE THREAD

**Issue by dianarypkema** [slucey/RpathDev#10]
Hi,

When I run the Rsim example
`REco.run1 <- rsim.run(REco.sim, method = 'RK4', years = 1:100)`

I get the error
```
Error in .Call("_Rpath_rk4_run", PACKAGE = "Rpath", params, instate, forcing,  : 
  "_Rpath_rk4_run" not available for .Call() for package "Rpath"
```

How can I fix this?

Thanks!
Diana

**Comment by slucey** [comment]
Hi Diana,

Sorry for the issue.  I'm not able to recreate that issue on my end.  Has everything else been running properly?  One suggestion would be to update your version of Rcpp.

Sean

**Comment by dianarypkema** [comment]
Hi Sean,

No worries--thanks for the recommendation! I updated Rcpp (and all the other packages I have installed) and now it works.

Thanks!
Diana

**Comment by slucey** [comment]
Excellent...let me know if you find any other bugs!
