### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by FMestre1** [slucey/RpathDev#11]
Hi there,

I've been trying to install your package but I get this error:
Error: HTTP error 404.
  No commit found for the ref public

This is the code I used:
devtools::install_github("slucey/RpathDev", ref= 'public')

If, instead, I use (upper case 'P'):
 devtools::install_github("slucey/RpathDev", ref= 'Public') 

I get this error:
Error: HTTP error 404.
  Not Found

Can you help me, please?

Cheers,
Frederico

**Comment by slucey** [comment]
Federico,

I apologize for the hassle.  This was the first repository I've made public
and have a bit of a learning curve.  The actual repo you need to navigate
to is 'slucey/RpathDev/Rpath'.  I will be fixing this issue soon by
migrating the code to a new repository prior to the paper submission
(hopefully by the end of the month or early May).

Sean


Sean M. Lucey
Fisheries Biologist
Ecosystem Dynamics and Assessment Branch
U. S. Dept. of Commerce/NOAA/NMFS
Northeast Fisheries Science Center
166 Water Street, Woods Hole, MA 02543
508-495-2011 (voice)
508-495-2232 (fax)

**Comment by FMestre1** [comment]
Thanks.
Now I'm getting a different error (sorry!)...
A message pops ups: "Building R package from source requires installation of additional build tools.
Do you want to install the additional tools now?"

If I select 'Yes' this is the error I get in R:
"Downloading GitHub repo slucey/RpathDev@Public
Error: Could not find tools necessary to compile a package"

Cheers,
frederico

**Comment by slucey** [comment]
Do you have the latest version of RTools installed?

**Comment by FMestre1** [comment]
I'll check.

**Comment by FMestre1** [comment]
Ok, thanks. The issue is solved. It had something to do with Rtools.
Cheers,
Frederico
