### ISSUE TITLE
Errors installing/building vignettes

### ISSUE THREAD

**Issue by raerickson** [slucey/RpathDev#7]
I tried to install the package in a Linux Docker (specifically, rocker/verse) image using 

    devtools::install_github('slucey/RpathDev/Rpath', ref = 'Public', build_vignettes = TRUE)

But I got this error message:

    * checking for file ‘/tmp/Rtmp2pcIM9/devtools945f438ad8/slucey-RpathDev- 9dddaa2/Rpath/DESCRIPTION’ ... OK
    * preparing ‘Rpath’:
    * checking DESCRIPTION meta-information ... OK
    * cleaning src
    * installing the package to build vignettes
    * creating vignettes ... ERROR
    Quitting from lines 182-184 (Rsim.Rmd) 
    Error: processing vignette 'Rsim.Rmd' failed with diagnostics:
    unused arguments (gear = "Trawlers", year = 25:100)
    Execution halted
    Installation failed: Command failed (1)

Does one of your vignettes need to be updated? If I use 

       devtools::install_github('slucey/RpathDev/Rpath', ref = 'Public', build_vignettes = FALSE)

The package builds without error.

**Comment by slucey** [comment]
Richard,

Thank you for flagging this.  A few changes to the Rsim code may have
broken the vignette.  I will update it and push the changes soon.

Sean


Sean M. Lucey
Fisheries Biologist
Ecosystem Dynamics and Assessment Branch
U. S. Dept. of Commerce/NOAA/NMFS
Northeast Fisheries Science Center
166 Water Street, Woods Hole, MA 02543
508-495-2011 (voice)
508-495-2232 (fax)
