### ISSUE TITLE
Citing Rpath?

### ISSUE THREAD

**Issue by seanhardison1** [slucey/RpathDev#9]
What's the best way to cite Rpath?

**Comment by slucey** [comment]
Right now the github site (slucey/RpathDev).  The paper should be submitted
soon.

Sean


Sean M. Lucey
Fisheries Biologist
Ecosystem Dynamics and Assessment Branch
U. S. Dept. of Commerce/NOAA/NMFS
Northeast Fisheries Science Center
166 Water Street, Woods Hole, MA 02543
508-495-2011 (voice)
508-495-2232 (fax)
